version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string

    docker:
      - image: cimg/ruby:<<parameters.ruby-version>>
    steps:
      - checkout
      - restore_cache:
          key: gc_ruboconfig-bundler-{{ checksum "gc_ruboconfig.gemspec" }}
      - run: gem install bundler
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install
      - save_cache:
          key: gc_ruboconfig-bundler-{{ checksum "gc_ruboconfig.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          command: |
            bundle exec ruby validate_config.rb

workflows:
  version: 2
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.6", "2.7", "3.0", "3.1"]
